Patch nginx to switch SIGTERM and SIGQUIT handlers.
Heroku expects SIGTERM to shutdown the application gracefully and
SIGQUIT to force the shutdown, nginx implements the opposite behavior.

diff --git a/scripts/build_nginx b/scripts/build_nginx
--- a/scripts/build_nginx
+++ b/scripts/build_nginx
@@ -6,50 +6,62 @@
 
 set -e
 
+out_dir=$1
+download_dir=/tmp/nginx-download
+release_dir=/tmp/nginx-release
+
 NGINX_VERSION=${NGINX_VERSION-1.25.2}
 
 
 nginx_tarball_url=https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
 
 rm -rf /tmp/nginx*
+mkdir ${download_dir} ${release_dir}
 
-temp_dir=$(mktemp -d /tmp/nginx-download.XXXXXXXXXX)
+cd ${download_dir}
 
-cd $temp_dir
-echo "Temp dir: $temp_dir"
-
-echo "Downloading $nginx_tarball_url"
+echo "Downloading $nginx_tarball_url to ${download_dir}"
 curl -L $nginx_tarball_url | tar xzv
 
+cd nginx-${NGINX_VERSION}
+
+# Heroku expects SIGTERM to shutdown the application gracefully and
+# SIGQUIT to force the shutdown, nginx implements the opposite
+# behavior.
+echo "Patching nginx to switch SIGTERM and SIGQUIT handlers"
+signal_defines_file="src/core/ngx_config.h"
+sed -i 's/#define\s\+NGX_TERMINATE_SIGNAL\s\+TERM/#define NGX_TERMINATE_SIGNAL QUIT \/\/remapped for Heroku/' \
+    ${signal_defines_file}
+sed -i 's/#define\s\+NGX_SHUTDOWN_SIGNAL\s\+QUIT/#define NGX_SHUTDOWN_SIGNAL TERM \/\/remapped for Heroku/' \
+    ${signal_defines_file}
+
+lines_patched=`grep 'remapped for Heroku' ${signal_defines_file}|wc -l|cut -f1 -d ' '`
+if (( ${lines_patched} != 2 )); then
+  echo "Failed to patch '${signal_defines_file}'"
+  exit 1
+fi
 
 # build `nginx`
-(
-  cd nginx-${NGINX_VERSION}
-  ./configure \
-    --with-http_auth_request_module \
-    --with-http_ssl_module \
-    --with-http_sub_module \
-    --prefix=/tmp/nginx
-  make install
-)
+./configure \
+  --with-http_auth_request_module \
+  --with-http_ssl_module \
+  --with-http_sub_module \
+  --prefix=/tmp/nginx
+make install
 
 
 # build `nginx-debug`
-(
-  cd nginx-${NGINX_VERSION}
-  ./configure \
-    --with-debug \
-    --with-http_auth_request_module \
-    --with-http_ssl_module \
-    --with-http_sub_module \
-    --prefix=/tmp/nginx-debug
-  make install
-)
+./configure \
+  --with-debug \
+  --with-http_auth_request_module \
+  --with-http_ssl_module \
+  --with-http_sub_module \
+  --prefix=/tmp/nginx-debug
+make install
 
-release_dir=$(mktemp -d /tmp/nginx-release.XXXXXXXXXX)
 
 cp /tmp/nginx/sbin/nginx $release_dir/nginx
 cp /tmp/nginx-debug/sbin/nginx $release_dir/nginx-debug
 cp /tmp/nginx/conf/mime.types $release_dir/mime.types
 tar -zcvf /tmp/nginx-"${STACK}".tgz -C $release_dir .
-cp /tmp/nginx-"${STACK}".tgz $1
+cp /tmp/nginx-"${STACK}".tgz ${out_dir}
